/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/avatar/index.vue')['default']
    Grid: typeof import('./src/hooks/Grid.tsx')['default']
    GridCell: typeof import('./src/hooks/GridCell.tsx')['default']
    GridContent: typeof import('./src/hooks/GridContent.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/hooks/Theme.tsx')['default']
  }
}
